apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rhoai-platform
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: rhoai-demo-foundations
spec:
  description: RHOAI operator and DataScienceCluster
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/dandawg/rhoai-deploy.git
    - https://github.com/dandawg/rhoai-demo-foundations.git
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
