apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-dsc-patch
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: ray-dsc-patch
    app.kubernetes.io/part-of: rhoai-demo-foundations
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: rhoai-distributed
  source:
    repoURL: https://github.com/redhat-ai-americas/rhoai-distributed.git
    targetRevision: main
    path: platform/ray
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
