apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hardware-profile-g4dn-xlarge
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: hardware-profile-g4dn-xlarge
    app.kubernetes.io/part-of: rhoai-demo-foundations
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: rhoai-serving
  source:
    repoURL: https://github.com/dandawg/rhoai-model-serving.git
    targetRevision: main
    path: platform/hardware-profiles/g4dn-xlarge
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
