apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-base-resources
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: model-base-resources
    app.kubernetes.io/part-of: rhoai-demo-foundations
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: rhoai-serving
  source:
    repoURL: https://github.com/dandawg/rhoai-model-serving.git
    targetRevision: main
    path: platform/models/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
